import json
import re
import zipfile
from collections import defaultdict
from docx import Document
from docx.oxml.ns import qn
from lxml import etree


def _parse_numbering(docx_path):
    """Parse word/numbering.xml from a .docx file.

    Returns {numId: {ilvl: {numFmt, lvlText, start}}}.
    """
    try:
        with zipfile.ZipFile(docx_path, 'r') as z:
            if 'word/numbering.xml' not in z.namelist():
                return {}
            numbering_xml = z.read('word/numbering.xml')
    except Exception:
        return {}

    root = etree.fromstring(numbering_xml)

    # Build abstractNumId → {ilvl: definition}
    abstract_nums = {}
    for abs_num in root.findall(qn('w:abstractNum')):
        abs_id = abs_num.get(qn('w:abstractNumId'))
        levels = {}
        for lvl in abs_num.findall(qn('w:lvl')):
            ilvl = int(lvl.get(qn('w:ilvl'), '0'))
            numFmt_el = lvl.find(qn('w:numFmt'))
            lvlText_el = lvl.find(qn('w:lvlText'))
            start_el = lvl.find(qn('w:start'))
            levels[ilvl] = {
                'numFmt': numFmt_el.get(qn('w:val')) if numFmt_el is not None else 'decimal',
                'lvlText': lvlText_el.get(qn('w:val')) if lvlText_el is not None else '%1.',
                'start': int(start_el.get(qn('w:val'))) if start_el is not None else 1,
            }
        abstract_nums[abs_id] = levels

    # Map numId → its abstractNum's level definitions
    result = {}
    for num in root.findall(qn('w:num')):
        num_id = int(num.get(qn('w:numId')))
        if num_id == 0:
            continue
        abs_ref = num.find(qn('w:abstractNumId'))
        if abs_ref is not None:
            abs_id = abs_ref.get(qn('w:val'))
            if abs_id in abstract_nums:
                result[num_id] = abstract_nums[abs_id]

    return result


def _get_numbering_text(p_el, numbering, counters):
    """Return formatted auto-numbering text for a paragraph, or None.

    Counters dict tracks (numId, ilvl) → how many paragraphs seen so far,
    so that each paragraph gets the correct incremental number.
    """
    pPr = p_el.find(qn('w:pPr'))
    if pPr is None:
        return None
    numPr = pPr.find(qn('w:numPr'))
    if numPr is None:
        return None
    numId_el = numPr.find(qn('w:numId'))
    if numId_el is None:
        return None
    num_id = int(numId_el.get(qn('w:val')))
    if num_id not in numbering:
        return None
    ilvl_el = numPr.find(qn('w:ilvl'))
    ilvl = int(ilvl_el.get(qn('w:val'))) if ilvl_el is not None else 0
    lvls = numbering[num_id]
    if ilvl not in lvls:
        return None
    lvl_def = lvls[ilvl]
    current = lvl_def['start'] + counters[num_id][ilvl]
    counters[num_id][ilvl] += 1
    num_text = lvl_def['lvlText'].replace('%1', str(current))
    return num_text


def _iter_body_paragraphs(doc, numbering=None):
    """Yield (text, runs, is_table_cell) for every paragraph in document body order.

    Includes both body <w:p> elements and <w:p> elements inside table cells.
    Each run is (text, is_underlined).

    When numbering is provided, auto-numbering text from w:numPr is prepended
    to paragraph text so that numbered list items match across template and
    document regardless of whether the number was typed as plain text or
    generated by Word's list auto-numbering.
    """
    counters = defaultdict(lambda: defaultdict(lambda: 0))
    for child in doc.element.body:
        tag = child.tag.split('}')[-1] if '}' in child.tag else child.tag
        if tag == 'p':
            text, runs = _parse_paragraph_xml(child)
            if numbering:
                num_text = _get_numbering_text(child, numbering, counters)
                if num_text:
                    text = num_text + text
            if text:
                yield text, runs, False
        elif tag == 'tbl':
            for cell in child.iter(qn('w:tc')):
                for p in cell.findall(qn('w:p')):
                    text, runs = _parse_paragraph_xml(p)
                    if numbering:
                        num_text = _get_numbering_text(p, numbering, counters)
                        if num_text:
                            text = num_text + text
                    if text:
                        yield text, runs, True


def _parse_paragraph_xml(p_el):
    """Extract text and runs from a <w:p> XML element.

    Uses iter() instead of findall() to include runs nested inside SDT
    (structured document tags), ins/del, and other wrapper elements, so
    the extracted text matches what mammoth.js produces in the frontend.
    """
    text_parts = []
    runs = []
    for r in p_el.iter(qn('w:r')):
        run_text = ''
        for t in r.findall(qn('w:t')):
            if t.text:
                run_text += t.text
        if run_text:
            rPr = r.find(qn('w:rPr'))
            is_under = rPr is not None and rPr.find(qn('w:u')) is not None
            runs.append((run_text, is_under))
            text_parts.append(run_text)
    full_text = ''.join(text_parts).strip()
    return full_text, runs


def _get_all_texts(doc, docx_path=None):
    """Return flat list of paragraph texts in document body order (includes table cells)."""
    numbering = _parse_numbering(docx_path) if docx_path else None
    return [text for text, _, _ in _iter_body_paragraphs(doc, numbering)]


class DocxParser:
    @staticmethod
    def parse(file_path: str) -> list[dict]:
        doc = Document(file_path)
        numbering = _parse_numbering(file_path)
        paragraphs = []
        for i, (text, runs, is_table_cell) in enumerate(_iter_body_paragraphs(doc, numbering)):
            underline_ranges = []
            pos = 0
            for run_text, is_under in runs:
                run_len = len(run_text)
                if is_under:
                    underline_ranges.append([pos, pos + run_len])
                pos += run_len
            paragraphs.append({
                "index": i,
                "text": text,
                "underline_ranges": underline_ranges,
                "is_table_cell": is_table_cell
            })
        return paragraphs

    @staticmethod
    def extract_full_text(file_path: str) -> str:
        doc = Document(file_path)
        return "\n".join(_get_all_texts(doc, file_path))

    @staticmethod
    def align_paragraphs(tpl_paras: list[dict], doc_paras: list[dict],
                         annotations: list[dict]) -> dict:
        """Align template paragraphs to document paragraphs using fixed-text regex matching.

        For each template paragraph, extracts the fixed-text skeleton (non-fillable
        segments) and uses it as a search pattern to find the corresponding document
        paragraph. No similarity thresholds — matching is deterministic.

        Returns {"mapping": {tpl_idx: doc_idx|None}, "inserted": [doc_idx, ...],
                 "optional_missing": set(tpl_idx)}
        where optional_missing are entirely-fillable non-required paragraphs that
        have no counterpart in the document and should NOT be reported as deleted.
        """
        ann_by_para: dict[int, list[dict]] = {}
        for a in annotations:
            if a.get("zone_type") != "fillable":
                continue
            ann_by_para.setdefault(a["paragraph_index"], []).append(a)

        # Identify entirely-fillable paragraphs where all fillable zones are optional
        optional_by_para: set[int] = set()
        for pi, anns in ann_by_para.items():
            # Para text is needed to check if fixed segments exist
            tpl_text = None
            for p in tpl_paras:
                if p["index"] == pi:
                    tpl_text = p["text"]
                    break
            if tpl_text is None:
                continue
            ranges = sorted(
                [(a["start_char"], a["end_char"]) for a in anns],
                key=lambda r: r[0])
            fixed_segments = []
            pos = 0
            for s, e in ranges:
                s = max(0, min(s, len(tpl_text)))
                e = max(s, min(e, len(tpl_text)))
                if pos < s:
                    fixed_segments.append(tpl_text[pos:s])
                pos = max(pos, e)
            if pos < len(tpl_text):
                fixed_segments.append(tpl_text[pos:])

            # Only entirely-fillable paragraphs (no fixed segments) can be optional
            if fixed_segments:
                continue
            # Check that NO fillable zone is required
            all_optional = True
            for a in anns:
                rules = a.get("rules", {})
                if isinstance(rules, str):
                    try:
                        rules = json.loads(rules)
                    except (json.JSONDecodeError, TypeError):
                        rules = {}
                if rules.get("required"):
                    all_optional = False
                    break
            if all_optional:
                optional_by_para.add(pi)

        doc_texts = [p["text"] for p in doc_paras]
        used_docs: set[int] = set()
        mapping: dict[int, int | None] = {}
        deferred: list[int] = []  # tpl indices that need positional fallback
        optional_missing: set[int] = set()

        # ── Pass 1: high-confidence matches ──
        for p in tpl_paras:
            pi = p["index"]
            text = p["text"]
            anns = ann_by_para.get(pi, [])
            found = None

            if not anns:
                # No fillable zones — exact, then substring, then high-similarity
                for j, dt in enumerate(doc_texts):
                    if j in used_docs:
                        continue
                    if dt == text:
                        found = j
                        break
                if found is None:
                    for j, dt in enumerate(doc_texts):
                        if j in used_docs:
                            continue
                        if text in dt or dt in text:
                            found = j
                            break
                if found is None:
                    from difflib import SequenceMatcher
                    best_j, best_r = None, 0.8
                    for j, dt in enumerate(doc_texts):
                        if j in used_docs:
                            continue
                        r = SequenceMatcher(None, text, dt).ratio()
                        if r > best_r:
                            best_j, best_r = j, r
                    found = best_j
            else:
                # Build fixed-text skeleton segments
                ranges = sorted(
                    [(a["start_char"], a["end_char"]) for a in anns],
                    key=lambda r: r[0])
                fixed_segments = []
                pos = 0
                for s, e in ranges:
                    s = max(0, min(s, len(text)))
                    e = max(s, min(e, len(text)))
                    if pos < s:
                        fixed_segments.append(text[pos:s])
                    pos = max(pos, e)
                if pos < len(text):
                    fixed_segments.append(text[pos:])

                if fixed_segments:
                    fixed_len = sum(len(s) for s in fixed_segments)
                    if fixed_len >= 2:
                        pattern = ".*?".join(re.escape(s) for s in fixed_segments)
                        for j, dt in enumerate(doc_texts):
                            if j in used_docs:
                                continue
                            if re.search(pattern, dt):
                                found = j
                                break
                    # If fixed text too short, defer to pass 2
                # Entirely fillable (no fixed segments) — defer to pass 2 positional
                # matching. Substring inclusion is too aggressive: pure-placeholder
                # text (e.g. "____") is a substring of any shorter placeholder,
                # producing false matches that cascade downstream.

            if found is not None:
                mapping[pi] = found
                used_docs.add(found)
            elif anns:
                # Only defer paragraphs with fillable zones — their content
                # legitimately differs between template and document
                deferred.append(pi)
            else:
                # Non-fillable paragraph with no match = genuinely deleted/modified
                mapping[pi] = None

        # ── Pass 2: positional fallback for deferred paragraphs ──
        # Match each deferred paragraph to the nearest unused document
        # paragraph after its preceding matched template paragraph, so that
        # deferred paragraphs from different sections don't cross-match.
        remaining_docs = sorted([j for j in range(len(doc_texts)) if j not in used_docs])
        for pi in sorted(deferred):
            prev_doc = None
            for tpl_idx in sorted(mapping.keys(), reverse=True):
                if tpl_idx < pi and mapping[tpl_idx] is not None:
                    prev_doc = mapping[tpl_idx]
                    break

            found = None
            for j in remaining_docs:
                if prev_doc is None or j > prev_doc:
                    found = j
                    break

            if found is not None:
                mapping[pi] = found
                used_docs.add(found)
                remaining_docs.remove(found)
            else:
                if pi in optional_by_para:
                    optional_missing.add(pi)
                mapping[pi] = None

        inserted = sorted(
            [j for j in range(len(doc_texts)) if j not in used_docs])

        # ── Pass 3: absorb adjacent inserted paragraphs into fillable template paragraphs ──
        fillable_coverage: dict[int, float] = {}
        for p in tpl_paras:
            pi = p["index"]
            text = p["text"]
            anns = ann_by_para.get(pi, [])
            if not anns or not text:
                fillable_coverage[pi] = 0.0
                continue
            total_fillable = sum(
                max(0, min(a["end_char"], len(text)) - max(0, a["start_char"]))
                for a in anns
            )
            fillable_coverage[pi] = total_fillable / len(text)

        rev_map: dict[int, int] = {}
        for tpl_idx, doc_idx in mapping.items():
            if doc_idx is not None:
                rev_map[doc_idx] = tpl_idx

        absorbed: dict[int, list[int]] = {}
        still_inserted: list[int] = []
        for doc_i in inserted:
            preceding_tpl = None
            for d in range(doc_i - 1, -1, -1):
                if d in rev_map:
                    preceding_tpl = rev_map[d]
                    break
            if preceding_tpl is not None and fillable_coverage.get(preceding_tpl, 0) >= 0.98:
                absorbed.setdefault(preceding_tpl, []).append(doc_i)
            else:
                still_inserted.append(doc_i)

        return {"mapping": mapping, "inserted": still_inserted, "absorbed": absorbed,
                "optional_missing": optional_missing}

    @staticmethod
    def extract_fillable_values(template_file_path: str, doc_file_path: str, annotations: list[dict]) -> dict:
        """Extract fillable values using regex context anchors.

        Builds a regex per paragraph from template fixed-text segments surrounding
        the fillable zones, then extracts variable-length content from the filled
        document. Falls back to character-slice on regex mismatch.

        Returns dict keyed by '{pi}_{start_char}' with shape:
            {"value": str, "doc_start": int, "doc_end": int}
        """
        template_doc = Document(template_file_path)
        doc_doc = Document(doc_file_path)
        tpl_texts = _get_all_texts(template_doc, template_file_path)
        doc_texts = _get_all_texts(doc_doc, doc_file_path)

        # Compute paragraph alignment
        tpl_paras = DocxParser.parse(template_file_path)
        doc_paras = DocxParser.parse(doc_file_path)
        alignment = DocxParser.align_paragraphs(tpl_paras, doc_paras, annotations)
        para_map = alignment["mapping"]
        absorbed = alignment.get("absorbed", {})

        values = {}

        ann_by_para: dict[int, list[dict]] = {}
        for ann in annotations:
            if ann.get("zone_type") != "fillable":
                continue
            pi = ann["paragraph_index"]
            ann_by_para.setdefault(pi, []).append(ann)

        for pi, anns in ann_by_para.items():
            if pi >= len(tpl_texts):
                continue
            doc_pi = para_map.get(pi)
            if doc_pi is None or doc_pi >= len(doc_texts):
                continue

            tpl_text = tpl_texts[pi]
            doc_text = doc_texts[doc_pi]
            # Merge absorbed paragraph text for fillable fields that span multiple doc paragraphs
            extra_paras = absorbed.get(pi, [])
            if extra_paras:
                merged = [doc_text] + [doc_texts[j] for j in sorted(extra_paras) if j < len(doc_texts)]
                doc_text = "\n".join(merged)
            if not tpl_text:
                continue

            anns_sorted = sorted(anns, key=lambda a: a.get("start_char", 0))
            tpl_len = len(tpl_text)

            fixed_parts = []
            pos = 0
            for ann in anns_sorted:
                start = max(0, min(ann.get("start_char", 0), tpl_len))
                end = max(start, min(ann.get("end_char", tpl_len), tpl_len))
                if pos < start:
                    fixed_parts.append(tpl_text[pos:start])
                else:
                    fixed_parts.append("")
                pos = max(pos, end)
            if pos < tpl_len:
                fixed_parts.append(tpl_text[pos:])
            else:
                fixed_parts.append("")

            escaped = [re.escape(p) for p in fixed_parts]
            pattern = "^" + "(.*?)".join(escaped) + "$"

            flags = re.DOTALL if extra_paras else 0
            match = re.search(pattern, doc_text, flags)
            if match:
                groups = match.groups()
                for i, ann in enumerate(anns_sorted):
                    key = f"{pi}_{ann.get('start_char', 0)}"
                    raw = groups[i] if i < len(groups) else ""
                    doc_start = match.start(i + 1) if i < len(groups) else 0
                    doc_end = match.end(i + 1) if i < len(groups) else 0
                    values[key] = {
                        "value": raw.strip(" _"),
                        "doc_start": doc_start,
                        "doc_end": doc_end
                    }
            else:
                for ann in anns_sorted:
                    tpl_start = max(0, min(ann.get("start_char", 0), len(doc_text)))
                    tpl_end = max(tpl_start, min(ann.get("end_char", len(doc_text)), len(doc_text)))
                    key = f"{pi}_{tpl_start}"
                    val = doc_text[tpl_start:tpl_end].strip(" _")
                    values[key] = {
                        "value": val,
                        "doc_start": tpl_start,
                        "doc_end": tpl_start + len(val)
                    }

        return values

    @staticmethod
    def detect_checkbox_status(template_file_path: str, doc_file_path: str,
                               annotations: list[dict]) -> dict:
        """Detect whether □ checkbox zones have been toggled to ☑ in the document.

        Only processes annotations whose rules include radio_group or checked=True.
        Returns dict keyed by '{pi}_{start_char}' with shape:
            {"checked": bool, "value": str, "doc_start": int, "doc_end": int}
        """
        CHECKED_CHARS = {'☑', '☒', '✓', '✔'}  # ☑ ☒ ✓ ✔

        template_doc = Document(template_file_path)
        doc_doc = Document(doc_file_path)
        tpl_texts = _get_all_texts(template_doc, template_file_path)
        doc_texts = _get_all_texts(doc_doc, doc_file_path)

        # Compute paragraph alignment
        tpl_paras = DocxParser.parse(template_file_path)
        doc_paras = DocxParser.parse(doc_file_path)
        alignment = DocxParser.align_paragraphs(tpl_paras, doc_paras, annotations)
        para_map = alignment["mapping"]

        # Filter to checkbox-relevant annotations
        checkbox_anns = []
        for ann in annotations:
            if ann.get("zone_type") != "fillable":
                continue
            rules = ann.get("rules", {})
            if isinstance(rules, str):
                try:
                    rules = json.loads(rules)
                except (json.JSONDecodeError, TypeError):
                    rules = {}
            if not rules or not isinstance(rules, dict):
                continue
            if rules.get("radio_group"):
                checkbox_anns.append(ann)

        statuses = {}
        for ann in checkbox_anns:
            pi = ann["paragraph_index"]
            if pi >= len(tpl_texts):
                continue
            doc_pi = para_map.get(pi)
            if doc_pi is None or doc_pi >= len(doc_texts):
                continue

            start = max(0, ann.get("start_char", 0))
            end = max(start + 1, ann.get("end_char", start + 1))
            doc_text = doc_texts[doc_pi]

            if start < len(doc_text):
                doc_char = doc_text[start:min(end, len(doc_text))]
            else:
                doc_char = ""

            key = f"{pi}_{start}"
            statuses[key] = {
                "checked": bool(doc_char and all(c in CHECKED_CHARS for c in doc_char)),
                "value": doc_char,
                "doc_start": start,
                "doc_end": min(end, len(doc_text))
            }

        return statuses
